In [5]:
import pandas as pd

In [6]:
dataset=pd.read_csv("insurance_pre.csv")

In [7]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [8]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [9]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [10]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [11]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes' ]]

In [12]:
dependent=dataset[['charges']]

In [13]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.03,random_state=0)

In [14]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train=sc.fit_transform(x_train)
x_test=sc.transform(x_test)

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestRegressor

param_grid = {
    'criterion': ['squared_error', 'absolute_error', 'friedman_mse', 'poisson'],
    'max_features': ['auto', 'sqrt', 'log2'],
    'n_estimators': [10, 100]
}

grid = GridSearchCV(RandomForestRegressor(), param_grid, refit=True, verbose=3, n_jobs=-1)

In [16]:
grid.fit(x_train,y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py:425: FitFailedWarning:
40 fits failed out of a total of 120.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
10 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'log2', 'sqrt'} or None. Got 'auto' instead.

--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\model_selection\_validation.py", line 732, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\base.py", line 1144, in wrapper
    estimator._validate_params()
  File "C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\base.py", line 637, in _validate_params
    validate_parameter_constraints(
  File "C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\utils\_param_validation.py", line 95, in validate_parameter_constraints
    raise InvalidParameterError(
sklearn.utils._param_validation.InvalidParameterError: The 'max_features' parameter of RandomForestRegressor must be an int in the range [1, inf), a float in the range (0.0, 1.0], a str among {'sqrt', 'log2'} or None. Got 'auto' instead.

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\model_selection\_search.py:976: UserWarning: One or more of the test scores are non-finite: [       nan        nan 0.81226045 0.82834544 0.81327407 0.83050422
        nan        nan 0.80786932 0.83002449 0.82005859 0.8312969
        nan        nan 0.81096273 0.83016907 0.81531491 0.83016311
        nan        nan 0.80537196 0.83177787 0.81692462 0.83078885]
  warnings.warn(
C:\Users\USER 10\anaconda3\Lib\site-packages\sklearn\base.py:1151: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return fit_method(estimator, *args, **kwargs)

GridSearchCV(estimator=RandomForestRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse', 'poisson'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'n_estimators': [10, 100]},
             verbose=3)

In [17]:
re=grid.cv_results_
print("The R_scoore value for best parameter{}:".format(grid.best_params_))

The R_scoore value for best parameter{'criterion': 'poisson', 'max_features': 'sqrt', 'n_estimators': 100}:

In [18]:
table=pd.DataFrame.from_dict(re)

In [19]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.000000,0.000000e+00,0.000000,0.000000,squared_error,auto,10,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
1,0.003125,6.250191e-03,0.000000,0.000000,squared_error,auto,100,"{'criterion': 'squared_error', 'max_features':...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
2,0.118741,2.538588e-02,0.003125,0.006249,squared_error,sqrt,10,"{'criterion': 'squared_error', 'max_features':...",0.876667,0.845778,0.758305,0.817746,0.762806,0.812260,0.046170,13
3,0.829184,1.533558e-02,0.028124,0.006250,squared_error,sqrt,100,"{'criterion': 'squared_error', 'max_features':...",0.886317,0.859406,0.769819,0.841773,0.784413,0.828345,0.044410,8
4,0.090618,6.250501e-03,0.000000,0.000000,squared_error,log2,10,"{'criterion': 'squared_error', 'max_features':...",0.873330,0.847973,0.757102,0.819357,0.768608,0.813274,0.044717,12
5,0.850166,3.132454e-02,0.024999,0.007654,squared_error,log2,100,"{'criterion': 'squared_error', 'max_features':...",0.887555,0.857397,0.778096,0.842307,0.787166,0.830504,0.041814,4
6,0.000000,0.000000e+00,0.000000,0.000000,absolute_error,auto,10,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
7,0.000000,0.000000e+00,0.000000,0.000000,absolute_error,auto,100,"{'criterion': 'absolute_error', 'max_features'...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
8,0.215610,6.250286e-03,0.006250,0.007654,absolute_error,sqrt,10,"{'criterion': 'absolute_error', 'max_features'...",0.878523,0.836732,0.742173,0.819719,0.762200,0.807869,0.049734,15
9,2.215470,3.336402e-02,0.031248,0.009881,absolute_error,sqrt,100,"{'criterion': 'absolute_error', 'max_features'...",0.891889,0.858020,0.776002,0.836940,0.787271,0.830024,0.043371,7
10,0.209360,7.653059e-03,0.000000,0.000000,absolute_error,log2,10,"{'criterion': 'absolute_error', 'max_features'...",0.890133,0.838897,0.764750,0.836641,0.769872,0.820059,0.047155,9
11,2.245657,8.619838e-02,0.028988,0.006887,absolute_error,log2,100,"{'criterion': 'absolute_error', 'max_features'...",0.894939,0.863767,0.774411,0.838382,0.784986,0.831297,0.045903,2
12,0.006250,7.654422e-03,0.000000,0.000000,friedman_mse,auto,10,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
13,0.000000,0.000000e+00,0.000000,0.000000,friedman_mse,auto,100,"{'criterion': 'friedman_mse', 'max_features': ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
14,0.089159,9.513723e-03,0.003125,0.006249,friedman_mse,sqrt,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.863836,0.829826,0.749672,0.829000,0.782480,0.810963,0.040111,14
15,0.876200,4.258197e-02,0.024999,0.007653,friedman_mse,sqrt,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.886325,0.861257,0.776981,0.842662,0.783620,0.830169,0.043062,5
16,0.081244,6.249404e-03,0.012500,0.006250,friedman_mse,log2,10,"{'criterion': 'friedman_mse', 'max_features': ...",0.871391,0.840031,0.759048,0.829681,0.776424,0.815315,0.041570,11
17,0.818693,7.653604e-03,0.028124,0.006250,friedman_mse,log2,100,"{'criterion': 'friedman_mse', 'max_features': ...",0.888450,0.856417,0.777719,0.838821,0.789409,0.830163,0.041407,6
18,0.003125,6.249809e-03,0.000000,0.000000,poisson,auto,10,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
19,0.000000,0.000000e+00,0.000000,0.000000,poisson,auto,100,"{'criterion': 'poisson', 'max_features': 'auto...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
20,0.106243,3.336409e-02,0.006250,0.007654,poisson,sqrt,10,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.876020,0.805981,0.762271,0.828433,0.754156,0.805372,0.044731,16
21,0.906186,7.893059e-07,0.021874,0.007655,poisson,sqrt,100,"{'criterion': 'poisson', 'max_features': 'sqrt...",0.892328,0.857540,0.779575,0.843586,0.785861,0.831778,0.043134,1
22,0.096868,6.250691e-03,0.003125,0.006249,poisson,log2,10,"{'criterion': 'poisson', 'max_features': 'log2...",0.880337,0.838061,0.780386,0.811835,0.774004,0.816925,0.039169,10
23,0.928942,7.067755e-02,0.025922,0.006542,poisson,log2,100,"{'criterion': 'poisson', 'max_features': 'log2...",0.889514,0.857467,0.775422,0.847343,0.784199,0.830789,0.043978,3

In [17]:
best_r2=grid.best_score_

In [18]:
best_r2

0.8321856065021469

In [19]:

age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
Children_input=float(input("children:"))
sex_male_input_input=float(input("sex male 0 or 1:"))
smoker_yes_input=float(input("smoker yes 0 or 1:"))

Age:28
BMI:60
children:1
sex male 0 or 1:0
smoker yes 0 or 1:0

In [20]:
Future_prediction=grid.predict([[age_input,bmi_input,Children_input,sex_male_input_input,smoker_yes_input]])
print("Future_prediction {}:",format(Future_prediction))

Future_prediction {}: [14058.11803395]